import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Clients from "./clients";
import Contact from "./contact";
import HomePage from "./homePage";
import Services from "./services";
import Work from "./work";





export default function Home() {
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
     
    </h1>
    <Navbar />
			<HomePage />
			<Services />
			<Work />
			<Clients />
			<Contact />
			<Footer />
      
    </div>
  )
}
